package com.linetv.demo.data.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.linetv.demo.data.db.DramasTable;

import com.linetv.demo.data.db.DramasTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dramasTableDaoConfig;

    private final DramasTableDao dramasTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dramasTableDaoConfig = daoConfigMap.get(DramasTableDao.class).clone();
        dramasTableDaoConfig.initIdentityScope(type);

        dramasTableDao = new DramasTableDao(dramasTableDaoConfig, this);

        registerDao(DramasTable.class, dramasTableDao);
    }
    
    public void clear() {
        dramasTableDaoConfig.clearIdentityScope();
    }

    public DramasTableDao getDramasTableDao() {
        return dramasTableDao;
    }

}
