package com.linetv.demo.data.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DRAMAS_TABLE".
*/
public class DramasTableDao extends AbstractDao<DramasTable, Long> {

    public static final String TABLENAME = "DRAMAS_TABLE";

    /**
     * Properties of entity DramasTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Drama_id = new Property(0, Long.class, "drama_id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Total_views = new Property(2, int.class, "total_views", false, "TOTAL_VIEWS");
        public final static Property Created_at = new Property(3, String.class, "created_at", false, "CREATED_AT");
        public final static Property Thumb_url = new Property(4, String.class, "thumb_url", false, "THUMB_URL");
        public final static Property Pic_name = new Property(5, String.class, "pic_name", false, "PIC_NAME");
        public final static Property Rating = new Property(6, double.class, "rating", false, "RATING");
    }


    public DramasTableDao(DaoConfig config) {
        super(config);
    }
    
    public DramasTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DRAMAS_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: drama_id
                "\"NAME\" TEXT," + // 1: name
                "\"TOTAL_VIEWS\" INTEGER NOT NULL ," + // 2: total_views
                "\"CREATED_AT\" TEXT," + // 3: created_at
                "\"THUMB_URL\" TEXT," + // 4: thumb_url
                "\"PIC_NAME\" TEXT," + // 5: pic_name
                "\"RATING\" REAL NOT NULL );"); // 6: rating
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DRAMAS_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DramasTable entity) {
        stmt.clearBindings();
 
        Long drama_id = entity.getDrama_id();
        if (drama_id != null) {
            stmt.bindLong(1, drama_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getTotal_views());
 
        String created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindString(4, created_at);
        }
 
        String thumb_url = entity.getThumb_url();
        if (thumb_url != null) {
            stmt.bindString(5, thumb_url);
        }
 
        String pic_name = entity.getPic_name();
        if (pic_name != null) {
            stmt.bindString(6, pic_name);
        }
        stmt.bindDouble(7, entity.getRating());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DramasTable entity) {
        stmt.clearBindings();
 
        Long drama_id = entity.getDrama_id();
        if (drama_id != null) {
            stmt.bindLong(1, drama_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getTotal_views());
 
        String created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindString(4, created_at);
        }
 
        String thumb_url = entity.getThumb_url();
        if (thumb_url != null) {
            stmt.bindString(5, thumb_url);
        }
 
        String pic_name = entity.getPic_name();
        if (pic_name != null) {
            stmt.bindString(6, pic_name);
        }
        stmt.bindDouble(7, entity.getRating());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DramasTable readEntity(Cursor cursor, int offset) {
        DramasTable entity = new DramasTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // drama_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // total_views
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // created_at
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // thumb_url
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // pic_name
            cursor.getDouble(offset + 6) // rating
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DramasTable entity, int offset) {
        entity.setDrama_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTotal_views(cursor.getInt(offset + 2));
        entity.setCreated_at(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setThumb_url(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPic_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRating(cursor.getDouble(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DramasTable entity, long rowId) {
        entity.setDrama_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DramasTable entity) {
        if(entity != null) {
            return entity.getDrama_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DramasTable entity) {
        return entity.getDrama_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
